services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-go-event-processor}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:8080:8080"
    environment:
      - DEBUG=${DEBUG:-0}
      - DYNAMO_TABLE_NAME=GoEvents
      - SERVICES=kinesis,lambda,dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"